#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

files=$(git diff --cached --name-only ':!*.json' ':!*gitignore*')
if [  -z "$files"]
then
      echo "\$files is empty"
else
      npx cspell -- $files
      npm run pre-commit
fi
